import Image from "next/image"
import Link from "next/link"
import { Bookmark, MapPin, Star } from "lucide-react"
import { prisma } from "@/lib/prisma"
import { requireRole } from "@/lib/session"
import { BackButton } from "@/components/back-button"

export default async function SavedProvidersPage() {
  const user = await requireRole("CUSTOMER")
  const saved = await prisma.savedProvider.findMany({ where: { customerId: user.id }, orderBy: { createdAt: "desc" }, include: { provider: { include: { user: { select: { name: true } } } } } })
  return <main className="min-h-screen bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><BackButton className="mb-4" /><p className="text-xs font-bold uppercase tracking-wider text-primary">Shortlist</p><h1 className="mt-1 text-3xl font-extrabold">Saved professionals</h1><p className="mt-1 text-sm text-muted-foreground">Keep trusted providers close for your next job.</p>{saved.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{saved.map(({ provider }) => <Link key={provider.id} href={`/pros/${provider.storeSlug}`} className="group overflow-hidden rounded-3xl border border-border bg-card shadow-sm transition hover:-translate-y-0.5 hover:border-primary/30"><div className="relative aspect-[16/10] bg-accent">{provider.coverImageUrl ? <Image src={provider.coverImageUrl} alt={provider.storeName ?? provider.user.name} fill sizes="360px" className="object-cover" /> : <Bookmark className="absolute inset-0 m-auto h-10 w-10 text-primary/30" />}</div><div className="p-4"><h2 className="font-bold">{provider.storeName ?? provider.user.name}</h2><div className="mt-2 flex gap-3 text-xs text-muted-foreground">{provider.totalReviews ? <span className="flex items-center gap-1"><Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />{provider.avgRating.toFixed(1)} <span className="text-muted-foreground">({provider.totalReviews})</span></span> : <span className="inline-flex items-center gap-1 rounded-full bg-accent px-2 py-0.5 font-semibold text-primary">New</span>}<span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{provider.locationLabel}</span></div></div></Link>)}</div> : <div className="mt-6 rounded-3xl border border-dashed border-border bg-card py-16 text-center"><Bookmark className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 font-semibold">No saved professionals</p><Link href="/search" className="mt-2 inline-block text-sm font-semibold text-primary">Browse providers</Link></div>}</div></main>
}
