"use client"

import { useState, useTransition } from "react"
import { AlertTriangle, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { resolveDispute } from "./actions"

type Item = { id: string; reason: string; details: string; status: "OPEN" | "REVIEWING" | "RESOLVED" | "DISMISSED"; resolution: string | null; customer: string; customerEmail: string; provider: string; amount: number | null; scheduledAt: string }
export function DisputesClient({ disputes }: { disputes: Item[] }) { const [notes, setNotes] = useState<Record<string,string>>({}); const [pending, startTransition] = useTransition(); return <div className="mx-auto max-w-6xl p-6"><p className="text-xs font-bold uppercase tracking-wider text-primary">Trust and safety</p><h1 className="mt-1 text-3xl font-extrabold">Disputes</h1><p className="mt-1 text-sm text-muted-foreground">Review customer issues and record a clear resolution.</p><div className="mt-6 space-y-4">{disputes.map((item) => <article key={item.id} className="rounded-3xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-500" /><h2 className="font-bold">{item.reason}</h2></div><p className="mt-1 text-xs text-muted-foreground">{item.customer} vs {item.provider} · {new Date(item.scheduledAt).toLocaleDateString("en-GH")}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs font-bold">{item.status}</span></div><p className="mt-4 text-sm leading-6">{item.details}</p>{item.status === "OPEN" || item.status === "REVIEWING" ? <div className="mt-4"><textarea value={notes[item.id] ?? ""} onChange={(e) => setNotes((current) => ({ ...current, [item.id]: e.target.value }))} rows={3} placeholder="Resolution notes for both parties" className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm" /><div className="mt-2 flex justify-end gap-2"><Button variant="outline" disabled={pending || (notes[item.id]?.length ?? 0) < 10} onClick={() => startTransition(async () => { await resolveDispute({ id: item.id, status: "DISMISSED", resolution: notes[item.id] }) })}>Dismiss</Button><Button disabled={pending || (notes[item.id]?.length ?? 0) < 10} onClick={() => startTransition(async () => { await resolveDispute({ id: item.id, status: "RESOLVED", resolution: notes[item.id] }) })}>{pending && <Loader2 className="animate-spin" />}Resolve</Button></div></div> : <p className="mt-4 rounded-xl bg-muted/40 p-3 text-sm"><strong>Resolution:</strong> {item.resolution}</p>}</article>)}</div></div> }
