"use client"

import { useState, useTransition } from "react"
import Link from "next/link"
import { ArrowLeft, Check, Loader2, ReceiptText } from "lucide-react"
import { Button } from "@/components/ui/button"
import { recordPayment } from "./actions"

type Item = { id: string; customerName: string; amount: number; status: "UNPAID" | "DEPOSIT_PAID" | "PAID" | "REFUNDED"; method: string | null; reference: string | null; date: string }
export function PaymentsClient({ bookings }: { bookings: Item[] }) { const [editing, setEditing] = useState<string | null>(null); const [method, setMethod] = useState("Mobile Money"); const [reference, setReference] = useState(""); const [pending, startTransition] = useTransition(); function save(id: string, status: Item["status"]) { startTransition(async () => { await recordPayment({ bookingId: id, status, method, reference }); setEditing(null); setReference("") }) } return <main className="min-h-screen bg-muted/20"><div className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><Link href="/provider" className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground"><ArrowLeft className="h-4 w-4" />Back to workspace</Link><header className="mt-5"><p className="text-xs font-bold uppercase tracking-wider text-primary">Financial records</p><h1 className="mt-1 text-3xl font-extrabold">Payments and receipts</h1><p className="mt-1 text-sm text-muted-foreground">Record offline or Mobile Money payments against completed jobs.</p></header><section className="mt-6 overflow-hidden rounded-3xl border border-border bg-card">{bookings.length ? <div className="divide-y divide-border">{bookings.map((item) => <article key={item.id} className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-bold">{item.customerName}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.date).toLocaleDateString("en-GH")}</p></div><div className="text-right"><p className="font-extrabold">GH₵{item.amount.toLocaleString()}</p><span className="text-xs font-semibold text-primary">{item.status.replaceAll("_", " ")}</span></div></div>{editing === item.id ? <div className="mt-4 grid gap-2 rounded-2xl bg-muted/30 p-4 sm:grid-cols-[1fr_1fr_auto]"><select value={method} onChange={(e) => setMethod(e.target.value)} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option>Mobile Money</option><option>Cash</option><option>Bank transfer</option></select><input value={reference} onChange={(e) => setReference(e.target.value)} placeholder="Transaction reference" className="h-10 rounded-xl border border-input bg-background px-3 text-sm" /><Button disabled={pending} onClick={() => save(item.id, "PAID")}>{pending ? <Loader2 className="animate-spin" /> : <Check className="h-4 w-4" />}Mark paid</Button></div> : <div className="mt-3 flex justify-end"><Button size="sm" variant="outline" onClick={() => setEditing(item.id)}><ReceiptText className="h-3.5 w-3.5" />Update payment</Button></div>}</article>)}</div> : <div className="py-16 text-center"><ReceiptText className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 font-semibold">No quoted jobs yet</p></div>}</section></div></main> }
